---
sidebar: sidebar 
permalink: ontap-security-hardening/autonomous-ransomware-protection.html 
keywords: tr-4569, ontap hardening guide, security, ARP, fpolicy, UBA, ransomware, machine learning, volume workloads, entropy 
summary: A funcionalidade de machine learning on-box do ONTAP deteta ransomware com base em cargas de trabalho de volume e entropia. 
---
= Proteção autônoma contra ransomware da ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para complementar a análise de comportamento do usuário para segurança de workloads de storage, a proteção autônoma contra ransomware do ONTAP analisa cargas de trabalho de volume e entropia para detectar ransomware, captura um snapshot e notifica o administrador quando um ataque é suspeito.

Além da detecção e prevenção de ransomware usando análise comportamental de usuário (UBA) externa do FPolicy com o NetApp Data Infrastructure Insights Storage Workload Security e o ecossistema de parceiros do NetApp FPolicy, o ONTAP 9.10.1 apresenta proteção autônoma contra ransomware.  A proteção autônoma contra ransomware do ONTAP usa um recurso integrado de aprendizado de máquina (ML) que analisa a atividade da carga de trabalho em volume, além da entropia de dados, para detectar ransomware automaticamente.  Ele monitora atividades diferentes do UBA para poder detectar ataques que o UBA não detecta.

Para obter informações mais detalhadas sobre essa capacidade, link:../ransomware-solutions/ransomware-overview.html["Soluções da NetApp para ransomware"] consulte ou link:https://docs.netapp.com/us-en/ontap/anti-ransomware/use-cases-restrictions-concept.html["Documentação autônoma de proteção de ransomware da ONTAP"^].
