---
permalink: zero-trust/zero-trust-automation-orchestration.html 
sidebar: sidebar 
keywords: tr-4829, zero trust, ontap, netapp, security, automation, orchestration, control, ansible 
summary: A automação permite que as organizações escalem implantações Zero Trust além dos procedimentos manuais para se defenderem de atividades mal criadas que também são automatizadas 
---
= Controles de orquestração e automação de segurança da NetApp externos ao ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A automação permite que você execute um processo ou procedimento com o mínimo de assistência humana. A automação permite que as organizações escalem implantações Zero Trust muito além dos procedimentos manuais para se defenderem de atividades maliciosas que também são automatizadas.

O Ansible é uma ferramenta de software livre para provisionamento, gerenciamento de configuração e implantação de aplicações. Ele roda em diversos sistemas do tipo Unix e pode configurar tanto sistemas Unix quanto Microsoft Windows. Inclui sua própria linguagem declarativa para descrever a configuração do sistema. O Ansible foi escrito por Michael DeHaan e adquirido pela Red Hat em 2015. O Ansible não utiliza agentes, conectando-se temporariamente de forma remota por meio de SSH ou Gerenciamento Remoto do Windows (permitindo execução remota do PowerShell) para realizar tarefas. NetApp desenvolveu mais de  https://www.netapp.com/devops/ansible/["150 módulos do Ansible para o software ONTAP"^], possibilitando maior integração com a estrutura de automação do Ansible. Os módulos Ansible para NetApp fornecem um conjunto de instruções sobre como definir o estado desejado e transmiti-lo ao ambiente de destino NetApp. Os módulos são criados para suportar tarefas como configuração de licenciamento, criação de agregados e máquinas virtuais de armazenamento, criação de volumes e restauração de snapshots, entre outras. Uma função Ansible foi  https://github.com/NetApp/ansible/tree/master/nar_ontap_security_ucd_guide["Publicado no GitHub"^] desenvolvida especificamente para o NetApp DoD Unified Capabilities (UC) Deployment Guide.

Ao usar a biblioteca de módulos disponíveis, os usuários podem facilmente desenvolver playbooks do Ansible e personalizá-los de acordo com suas próprias aplicações e necessidades empresariais para automatizar tarefas mundanas. Depois que um manual é escrito, você pode executá-lo para executar a tarefa especificada, o que economiza tempo e melhora a produtividade. A NetApp criou e compartilhou exemplos de playbooks que podem ser usados diretamente ou personalizados para suas necessidades.

O Data Infrastructure Insights é uma ferramenta de monitoramento de infraestrutura que oferece visibilidade de toda a sua infraestrutura.  Com o Data Infrastructure Insights, você pode monitorar, solucionar problemas e otimizar todos os seus recursos, incluindo suas instâncias de nuvem pública e seus data centers privados.  O Data Infrastructure Insights pode reduzir o tempo médio de resolução em 90% e evitar que 80% dos problemas de nuvem afetem os usuários finais.  Ele também pode reduzir os custos de infraestrutura de nuvem em uma média de 33% e diminuir sua exposição a ameaças internas protegendo seus dados com inteligência acionável.  O recurso de segurança de carga de trabalho de armazenamento do Data Infrastructure Insights permite análises comportamentais do usuário com IA e ML para alertar quando comportamentos anormais do usuário ocorrem devido a uma ameaça interna.  Para o ONTAP, o Storage Workload Security utiliza o mecanismo Zero Trust FPolicy.
