---
permalink: zero-trust/zero-trust-cloud-deployments.html 
sidebar: sidebar 
keywords: tr-4829, zero trust, netapp, cloud, deployments, hybrid, amazon web services, aws, microsoft azure, google cloud platform, gcp, GCNV, Google Cloud, Google Cloud NetApp Volumes 
summary: As opções do NetApp estendem os sistemas de gerenciamento de dados locais até a nuvem híbrida, com os principais fornecedores de nuvem, compatíveis com controles de segurança de confiança zero 
---
= Implantações de nuvem híbrida e de confiança zero
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A NetApp é a autoridade em dados para a nuvem híbrida. A NetApp oferece uma variedade de opções para estender sistemas de gerenciamento de dados locais para a nuvem híbrida com Amazon Web Services (AWS), Microsoft Azure, Google Cloud e outros provedores de nuvem líderes. As soluções de nuvem híbrida da NetApp oferecem suporte aos mesmos controles de segurança Zero Trust disponíveis nos sistemas ONTAP locais e no armazenamento definido por software ONTAP Select .

Você pode expandir facilmente a capacidade em nuvens públicas sem as restrições típicas de CAPEX usando serviços de arquivo nativos em nuvem de nível empresarial para AWS (FSxN), Google Cloud (GCNV) e Azure NetApp Files para Microsoft Azure. Ideais para cargas de trabalho com uso intensivo de dados, como análise e DevOps, esses serviços de dados em nuvem combinam armazenamento elástico e sob demanda como serviço da NetApp com gerenciamento de dados ONTAP em uma oferta totalmente gerenciada.

O ONTAP permite a movimentação de dados entre seus sistemas ONTAP locais e o ambiente de armazenamento AWS, Google Cloud ou Azure com o software de replicação de dados NetApp SnapMirror .
